### PR TITLE
LinkedIn Config

### PR DESCRIPTION
**Pull request by Misioka**
Add LinkedIn app ClientId and Secret

### CODE REVIEW

**Comment by jodybrewster** [comment]
So I've removed clientid and secret since this project is still on oauth1.  You just need this so it won't break you build?

**Comment by Misioka** [comment]
I don't understand your question, sorry.

**Comment by jodybrewster** [comment]
I have recently removed the clientid and secret since its not needed.  Why would you like to add it back since its not being used by Android and iOS?

**Comment by Misioka** [comment]
I've added them bac because it's not working without them at all

**Comment by jodybrewster** [comment]
I've removed the client secret based on requests from other users.  Its not secure and not recommended to keep it in your app. If you're ok with your app having the client secret I would either fork this project or keep your package.json reference hard set at the version you had before I implemented the fix. I would however recommend you update the your project by following the current readme instructions.

**Pull request closed without merging**
